### ISSUE TITLE
When can I get all the code?

### ISSUE THREAD

**Issue by qingquan6xiang** [WHU-USI3DV/MENet#1]
Your research success is commendable, but I have some coding issues. When can I get all the code? How can I get the bevfusionb and type="BEVFusion" and type="ConvMapEncoder" in the model? I hope you can take your time to solve them.

**Comment by YuanxianH** [comment]
Sorry for the late reply. We plan to release the whole code base in the Chinese Spring Festival.

**Comment by YuanxianH** [comment]
> Your research success is commendable, but I have some coding issues. When can I get all the code? How can I get the bevfusionb and type="BEVFusion" and type="ConvMapEncoder" in the model? I hope you can take your time to solve them.

The code has been open-sourced.

**Comment by qingquan6xiang** [comment]
Oh~thank you very much




刘响
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WHU-USI3DV/MENet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月14日(星期三) 晚上6:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [WHU-USI3DV/MENet] When can I get all the code? (Issue #1)





 
Closed #1 as completed.
